import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Save, ShieldAlert, SlidersHorizontal } from 'lucide-react';
import { assistantApi } from '../data/AssistantApi';
import { LoadingState } from '../components/LoadingState';

/** Gives the owner a deliberate, low-noise space for global rules and contact safeguards. */
export function SettingsPage(): JSX.Element {
  const queryClient = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['settings'], queryFn: () => assistantApi.getSettings() });
  const [form, setForm] = useState<Record<string, string | number | boolean | null>>({});
  useEffect(() => { if (data?.settings) setForm(data.settings); }, [data]);
  const save = useMutation({ mutationFn: () => assistantApi.saveSettings(form), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['settings'] }); void queryClient.invalidateQueries({ queryKey: ['overview'] }); } });
  const contact = useMutation({ mutationFn: ({ id, values }: { id: string; values: Record<string, unknown> }) => assistantApi.updateContact(id, values), onSuccess: () => { void queryClient.invalidateQueries({ queryKey: ['settings'] }); void queryClient.invalidateQueries({ queryKey: ['conversations'] }); } });
  if (isLoading) return <LoadingState />;
  const submit = (event: FormEvent<HTMLFormElement>): void => { event.preventDefault(); save.mutate(); };
  return <section className="settings-page"><header className="page-header"><div><p className="eyebrow">CONTROL ROOM</p><h1>Set the rules once.</h1><p className="subtle">Relay follows your tone, timing, and boundaries on every reply.</p></div></header><form className="settings-grid" onSubmit={submit}><section className="settings-card settings-card--wide"><div className="settings-card__title"><SlidersHorizontal size={18} /><div><h2>Reply behavior</h2><p>How your assistant should sound and operate by default.</p></div></div><label className="field-label">System instructions<textarea value={String(form.system_prompt ?? '')} onChange={(event) => setForm({ ...form, system_prompt: event.target.value })} rows={5} maxLength={4000} /></label><div className="field-row"><label className="field-label">Default workflow<select value={String(form.default_mode ?? 'auto')} onChange={(event) => setForm({ ...form, default_mode: event.target.value })}><option value="auto">Automatic reply</option><option value="manual">Approval required</option></select></label><label className="field-label">Reply delay (seconds)<input min="0" max="3600" type="number" value={Number(form.reply_delay_seconds ?? 0)} onChange={(event) => setForm({ ...form, reply_delay_seconds: Number(event.target.value) })} /></label></div><div className="field-row"><label className="field-label">Working hours start<input type="time" value={String(form.working_hours_start ?? '')} onChange={(event) => setForm({ ...form, working_hours_start: event.target.value || null })} /></label><label className="field-label">Working hours end<input type="time" value={String(form.working_hours_end ?? '')} onChange={(event) => setForm({ ...form, working_hours_end: event.target.value || null })} /></label></div><button className="button button--primary" disabled={save.isPending}><Save size={16} />{save.isPending ? 'Saving…' : 'Save preferences'}</button></section><section className="settings-card"><div className="settings-card__title"><ShieldAlert size={18} /><div><h2>Contact guardrails</h2><p>Fine-grained exceptions always win over defaults.</p></div></div><div className="contact-rules">{data?.contacts.map((item) => <article key={item.id} className="contact-rule"><div><strong>{item.display_name ?? `+${item.phone}`}</strong><span>+{item.phone}</span></div><label><input checked={item.is_blacklisted} type="checkbox" onChange={(event) => contact.mutate({ id: item.id, values: { is_blacklisted: event.target.checked } })} /> Block replies</label><select value={item.bot_mode} onChange={(event) => contact.mutate({ id: item.id, values: { bot_mode: event.target.value } })}><option value="inherit">Inherit</option><option value="auto">Automatic</option><option value="manual">Manual</option><option value="off">Off</option></select></article>)}{!data?.contacts.length && <p className="subtle">Contacts will be listed after the first incoming message.</p>}</div></section></form></section>;
}
